language: go
addons:
  apt:
    packages:
    - bsdtar
sudo: false
go:
- 1.8
install:
- ./tools/build.sh
- ./tools/package.sh
script:
- ./tools/test.sh
after_success:
- bash <(curl -s https://codecov.io/bash) -t 6259c706-5c1d-471f-b62b-4f908ea1801d
notifications:
  slack:
    secure: ejZnsyfPz7eRd0EyUfWD07Qy8cV12IfYQARcVSIjGxxPp5AOoZ96TPsE5W+GUD2XxGhzcGbXzMhZHE2cu2icC7NBjpuQuWP9o56cR6lz5qwpz5TbE7Q3GIxPWaWjkLGnr+OHymqXHCk6ArLoDVWiUeOoJXrL6MgHnNXOmIez3o6yQMvW03K2P095G9saG8LKx7AxNLBXTJUHgKiiQJ8VrsK8uOKmumG/mbUoh8jG5TtUVK8g7m7ye11kiocvezJwNlRsjdGsBNlzJoL4EB5d47hD2xQ9LoGgLp6HvGXGk0Zun4ZvXkP1b3WeUqxkmaRCaRKH8ESMEekZ3bab2dAtd858PPoofNYfc94T2TSug5Zc4EfMniLUv1NZByono4deLhzFPnolDXdRE+rxtmRhw4ubp281tYgiZFJ2ZFqbMlHHsQjMLNLlKNpFnxmKaWdwR8lgYkyHatEReZUbyDxrAUmfUYGKHy8RQNmWEz17d2yg8gnNYqp7jD86cHZrAUGowaoT3kwYb6yHkfWtEu1UyzQOrEtM4tSPC7ZnZT9HT3/Wn6EVl58cFisDKL/ta1LxKLACrbroZvkZ2W74jJ1X7juGrNE7qrZ493xyzYEZ6tFF0JD5Nz2USKaDFuCfGtMAjkAia4IQJl+5pNc+nzGHdWW92ESqQGyL2nUTDzsW+aY=
deploy:
  provider: releases
  api_key:
    secure: P3pJaK+kWz8gH6NNOtCuFM6tcoKvmlFxpNF43wdlBU4AMIbrhcIhh8hU3UB2x6YUYq4kD8tlIWwQOUzZ89kOwu+InCb2hmgBe+MtXKxJEQeucp8OYOmGpY85tMg13ZTF/HJt8S97xy/ofRUbfyQn8NQgC8B5bPBG7q/CnaUVqVw5YAmG8AowQvSIP7dL7OSkhv5c2bq/kSdZn7nFC2iY+7oCOr254nQuMHIKd+EA+my+WTx99U528+GsbX8CMlb7O2Nf0Xwtd1mcjawJLinAGyvqbYiC2igq5c6iA9Vl9BPUJNfuhoB5eX3NMUZ6MLH9epJ1Vo6fBinBGtywiCrazqAzCCS1EZZ57LlLZJEl7JwaQ2C7YP2MzyPbYyhlhdUMTZ0DPqnrAHBIm6gEj9Zd5RgS2Z6VPEWDuWtnPh3yjWXuHKoHI2TWWB7/tCCgzxgYM/6EKausz9xCfMnST8oaEz7sGNVXUOQWlK20qm+oix5m46MMcZSPAOWBwg4Oj7o5SBUg9TBE+ZgyG7qYYt7K1T4D2MQGPPWkfA/Xlw0+01fElct59kJO/qhuE+xHJfOUw6hpmoI4VgRtXAZqa60RJMDgF2Yj+yOjIBvlKoZH2IZh1I2rTMCHkE6pNoD1NKJXpsT2C5x7NiWhsbXE0dbqV0G9Vve0jBmYxPc1xOhgJ1U=
  file:
    - dr-provision.zip
    - dr-provision.sha256
  on:
    repo: digitalrebar/provision
    tags: true
