language: go
addons:
  apt:
    packages:
    - bsdtar
sudo: false
go:
- 1.8
install:
- ./tools/build.sh
- ./tools/package.sh
script:
- ./tools/test.sh
after_success:
- bash <(curl -s https://codecov.io/bash) -t 6259c706-5c1d-471f-b62b-4f908ea1801d
notifications:
  slack:
    secure: ejZnsyfPz7eRd0EyUfWD07Qy8cV12IfYQARcVSIjGxxPp5AOoZ96TPsE5W+GUD2XxGhzcGbXzMhZHE2cu2icC7NBjpuQuWP9o56cR6lz5qwpz5TbE7Q3GIxPWaWjkLGnr+OHymqXHCk6ArLoDVWiUeOoJXrL6MgHnNXOmIez3o6yQMvW03K2P095G9saG8LKx7AxNLBXTJUHgKiiQJ8VrsK8uOKmumG/mbUoh8jG5TtUVK8g7m7ye11kiocvezJwNlRsjdGsBNlzJoL4EB5d47hD2xQ9LoGgLp6HvGXGk0Zun4ZvXkP1b3WeUqxkmaRCaRKH8ESMEekZ3bab2dAtd858PPoofNYfc94T2TSug5Zc4EfMniLUv1NZByono4deLhzFPnolDXdRE+rxtmRhw4ubp281tYgiZFJ2ZFqbMlHHsQjMLNLlKNpFnxmKaWdwR8lgYkyHatEReZUbyDxrAUmfUYGKHy8RQNmWEz17d2yg8gnNYqp7jD86cHZrAUGowaoT3kwYb6yHkfWtEu1UyzQOrEtM4tSPC7ZnZT9HT3/Wn6EVl58cFisDKL/ta1LxKLACrbroZvkZ2W74jJ1X7juGrNE7qrZ493xyzYEZ6tFF0JD5Nz2USKaDFuCfGtMAjkAia4IQJl+5pNc+nzGHdWW92ESqQGyL2nUTDzsW+aY=
deploy:
  provider: releases
  api_key:
    secure: qdX7rFhTWwwKCFNTAofzV+ln67fnn/ANDqfKcowjJAVWcv6cJ56Rg5Q9N0lL9y0wBzxRHM5yRCJKJGp432VC89l9ZWN2sSoNcZbQt/hLBAymP4F3KhGDQWFgKVo+JbzHvYCFuLm3pyyAZ8HrhOZZgv8vW76AXtFNhDmM7fB+LpkBHaFx/T2MiabAm1O2CLZJbk4AGq/Ach42FjGRSMxIIcsR3Ud82zrqjktgXm3jiv9t4aCghkiBh5JqisDhBVAFtfmAncgKhjBqMG5K4R2LpVhlFPLs9Y+kEE02/8c089gHPNYhDwZLbfyUF72lyuQ5H0sqSe/JGKUOgpGcSiafCy0gYGiLEH1vqxqkfdcGybS67dv09pPTos4ke0Nv+7feFFEzE6eplT1r2sDadIxFfp8e8mgW+NsbSY/Pgs7hGvi8K/qc2Zy/PRCZzAAOI3/QhpsxAowv+7TG27y1Z6SYTvqpJRL4Hr61P0UA8EUDeYTn5jdQKJss2kDB8QfNwyshDBR56rAlDZQoYuYl8w7hLLpUhdcQjnDQ3126f9EVDVgwYL43NIUehWoSU0Fq+5oGykn6bDY8QkPBUa3vpBrtRZmt3zF4OOlP8Kn9gc9Xr1+8ItBh3bXJFuHm4CN6JFCGS4aamEYQA/CK5x5WquA+ezyUbKVaKrfsBXGg5gKONZQ=
  file:
    - dr-provision.zip
    - dr-provision.sha256
  skip_cleanup: true
  on:
    repo: digitalrebar/provision
    tags: true
