language: go

sudo: false

go:
- 1.8

install:
- ./tools/build.sh

script:
- ./tools/test.sh

after_success:
- bash <(curl -s https://codecov.io/bash) -t 6259c706-5c1d-471f-b62b-4f908ea1801d

notifications:
  slack:
    secure: ejZnsyfPz7eRd0EyUfWD07Qy8cV12IfYQARcVSIjGxxPp5AOoZ96TPsE5W+GUD2XxGhzcGbXzMhZHE2cu2icC7NBjpuQuWP9o56cR6lz5qwpz5TbE7Q3GIxPWaWjkLGnr+OHymqXHCk6ArLoDVWiUeOoJXrL6MgHnNXOmIez3o6yQMvW03K2P095G9saG8LKx7AxNLBXTJUHgKiiQJ8VrsK8uOKmumG/mbUoh8jG5TtUVK8g7m7ye11kiocvezJwNlRsjdGsBNlzJoL4EB5d47hD2xQ9LoGgLp6HvGXGk0Zun4ZvXkP1b3WeUqxkmaRCaRKH8ESMEekZ3bab2dAtd858PPoofNYfc94T2TSug5Zc4EfMniLUv1NZByono4deLhzFPnolDXdRE+rxtmRhw4ubp281tYgiZFJ2ZFqbMlHHsQjMLNLlKNpFnxmKaWdwR8lgYkyHatEReZUbyDxrAUmfUYGKHy8RQNmWEz17d2yg8gnNYqp7jD86cHZrAUGowaoT3kwYb6yHkfWtEu1UyzQOrEtM4tSPC7ZnZT9HT3/Wn6EVl58cFisDKL/ta1LxKLACrbroZvkZ2W74jJ1X7juGrNE7qrZ493xyzYEZ6tFF0JD5Nz2USKaDFuCfGtMAjkAia4IQJl+5pNc+nzGHdWW92ESqQGyL2nUTDzsW+aY=
